# Generated by Django 4.0.6 on 2022-08-10 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifierApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(upload_to='userZip/', validators=[django.core.validators.FileExtensionValidator(['zip'])])),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to='userPics/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
