# Generated by Django 4.1 on 2022-08-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifierApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=150)),
                ('start_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humid', models.IntegerField()),
                ('pH', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('date_field', models.DateField(auto_now=True)),
                ('road_len_const', models.IntegerField()),
                ('p_name', models.CharField(max_length=150)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassifierApi.project')),
            ],
        ),
    ]
