# Generated by Django 4.1 on 2022-08-25 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifierApi', '0002_project_project_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='zipFile_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(upload_to='userZip/', validators=[django.core.validators.FileExtensionValidator(['zip'])])),
                ('csv', models.FileField(upload_to='userZip/csv', validators=[django.core.validators.FileExtensionValidator(['csv', 'xlsx'])])),
            ],
        ),
    ]
