# Generated by Django 4.1 on 2022-08-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifierApi', '0003_zipfile_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=2)),
                ('lng', models.FloatField(default=2)),
                ('date', models.DateField(auto_now=True)),
                ('route', models.CharField(default=2, max_length=150)),
                ('cityAdress', models.CharField(default=2, max_length=150)),
                ('stateAdress', models.CharField(default=2, max_length=150)),
                ('countryAdress', models.CharField(default=2, max_length=150)),
                ('postaladd', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('first_Name', models.CharField(max_length=150)),
                ('last_Name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='project_det',
            name='p_no',
            field=models.IntegerField(default=0),
        ),
    ]
