# Generated by Django 4.1 on 2022-08-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifierApi', '0004_latlng_users_project_det_p_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_det',
            name='p_id',
            field=models.IntegerField(default=0),
        ),
    ]
